library(dplyr)
library("rio")
library(googleVis)
library(reshape)
library(reldist)
library(leaflet)
library(RColorBrewer)
library(scales)
library(lattice)
library(googleCharts)
library(ggplot2)
library(readr)

convert("data/bigdata.csv","data/bigdata.rds")
convert("data/ccpidata.csv","data/ccpidata.rds")
convert("data/gdpdata.csv","data/gdpdata.rds")
convert("data/literacydata.csv","data/literacydata.rds")


bigdata <- readRDS("data/bigdata.rds")
bigdataf <- data.frame(readRDS("data/bigdata.rds"))
ccpidata<-data.frame(readRDS("data/ccpidata.rds"))
gdpdata<-data.frame(readRDS("data/gdpdata.rds"))
lrdata<-data.frame(read.csv("data/lrdata.csv"))
GDP <- data.frame(read.csv("data/GDP.csv"))
Gini <- data.frame(read.csv("data/Gini.csv"))
literacydata <- readRDS("data/literacydata.rds")
lr2 <-data.frame(read.csv("data/plot1.csv"))
lr_truncated<-data.frame(read.csv("data/plot2.csv"))
haqidata <- data.frame(read.csv("data/haqidata.csv"))
haqi <- data.frame(read.csv("data/haqi.csv"))
haqi2 <- data.frame(read.csv("data/haqi2.csv"))
lrhistdata <- read.csv("data/lrhistdata.csv")
adultpophistdata <- read.csv("data/adultpophistdata.csv")

bigdata$region <- as.factor(bigdata$region)
literacydata$region <- as.factor(literacydata$region)
bigdata$latitude <- jitter(bigdata$latitude)
bigdata$longitude <- jitter(bigdata$longitude)
bigdata$countrycode <- formatC(bigdata$countrycode, width=5, format="d", flag="0")
row.names(bigdata) <- bigdata$countrycode
